#!/usr/bin/env bash

if [ $# == 0 ]
then
  echo "usage: $0 number"
  exit 1
fi

if [ $1 == 1 ]
then
  CONFFILE=configs/examples/client1.yaml
elif [ $1 == 2 ]
then
  CONFFILE=configs/examples/client2.yaml
elif [ $1 == 3 ]
then
  CONFFILE=configs/examples/client3.yaml
elif [ $1 == 4 ]
then
  CONFFILE=configs/examples/client4.yaml
else
  echo "illegal client number $1: must be one of 1..4"
  exit 1
fi

echo "Configuration file is $CONFFILE."
echo "Client will be started."

python src/cgosclient.py $CONFFILE &
