#
# cgos13.yaml -- CGOS server config for boardsize 13x13
#

# serverName: descriptive name of server for sgf and html pages
# type: str, required
serverName: "(CGOS) 13x13 Computer Go Server"

# boardsize: size of the Go board
# type: int, required
boardsize: 13

# komi: Komi value
# type: float, required
komi: 7.0

# koRule: Ko rule in effect
# type: str, optional (default: "POSITIONAL")
# possible values: "SIMPLE", "POSITIONAL"
koRule: "POSITIONAL"

# level: time limit, in seconds
# type: int, required
level: 600

# portNumber: port number this server is listening on
# type: int, required
portNumber: 6813

# timeGift: Fischer timing increment, in seconds
# type: float, required
timeGift: 0.25

# logging_directory: directory of logging files
# type: str, required
logging_directory: "../server-data/13x13/logs"

# logging_filename: base name of logging files
# type: str, required
logging_filename: "cgos_server.log"

# database_state_file: ???
# type: str, required
database_state_file: "../server-data/13x13/state.db"

# game_archive_database: ???
# type: str, optional (default: null)
game_archive_database: "../server-data/13x13/archive.db"

# web_data_file: ???
# type: str, required
web_data_file: "../server-data/13x13/wdata.txt"

# defaultRating: rating a client starts with
# type: float, required
defaultRating: 1800.0

# minK: minimum value of the K-factor
# type: float, required
minK: 3.0

# maxK: maximum value of the K-factor
# type: float, required
maxK: 200.0

# htmlDir: directory for storing WEB pages
# type: str, required
htmlDir: "/var/www/html/13x13"

# htmlInfoMsg: ???
# type: str, required
htmlInfoMsg: "Boardsize 13x13 - Komi 7.0 - 10 minutes per side"

# sgfDir: ???
# type: str, required
sgfDir: "SGF"

# compressSgf: should the SGF records be compressed?
# type: bool, optional (default: false)
compressSgf: true

# provisionalAge: days an entry will stay on WEB page if no games played
# type: float, required
provisionalAge: 0.04

# establishedAge: days an entry will stay on WEB page if no games played
# type: float, required
establishedAge: 31.0

# killFileSrv: existence of this file stops scheduling games and
#              shuts down the server after all games are completed
# type: str, required
killFileSrv: "./kill_cgos13"

# killFileWeb: existence of this file shuts down the WEB page builder
# type: str, required
killFileWeb: "./kill_webuild13"

# anchor_trigger_file: existence of this file triggers setting of anchors
# type: str, required
anchor_trigger_file: "./set_anchors13"

# anchor_ratings_file: anchor players file, together with their ratings
# type: str, required
anchor_ratings_file: "./anchors/anchors13"

# anchor_match_rate: ???
# type: float, optional (default: 0.10)
anchor_match_rate: 0.10

# bad_users_file: file with user names which are not allowed to connect
# type: str, optional (default: null)
bad_users_file: null

# moves_per_save: ???
# type: int, optional (default: 1)
moves_per_save: 1

# hashPassword: store hashed password
# type: bool, optional (default: false)
hashPassword: false

# matchMode: determines who matches players
# type: str, optional (default: "AUTO")
# possible values: "AUTO", "ADMIN"
matchMode: "AUTO"
