#
# cgos19.yaml -- CGOS server config for boardsize 19x19
#

# ???
# type: str
# required
serverName: "(CGOS) 19x19 Computer Go Server"

#!!! TO BE DELETED !!!
# ???
# type: str
# required
rule: "NONSENSE"

# ???
# type: int
# required
boardsize: 19

# ???
# type: float
# required
komi: 7.0

# ???
# type: str
# optional
# default: "POSITIONAL"
# possible values: "SIMPLE", "POSITIONAL"
koRule: "POSITIONAL"

# ???
# type: int
# required
level: 900

# ???
# type: int
# required
portNumber: 6819

# ???
# type: float
# required
timeGift: 0.25

# ???
# type: str
logging_directory: "<server-data>/19x19/logs"

# ???
# type: str
logging_filename: "cgos_server.log"

# ???
# type: str
# required
database_state_file: "<server-data>/19x19/state.db"

# ???
# type: str
# optional
# default: null
game_archive_database: "<server-data>/19x19/archive.db"

# ???
# type: str
# required
web_data_file: "<server-data>/19x19/wdata.txt"

# ???
# type: float
# required
defaultRating: 1800.0

# ???
# type: float
# required
minK: 3.0

# ???
# type: float
# required
maxK: 200.0

# ???
# type: str
# required
htmlDir: "<server-html>/19x19"

# ???
# type: str
# required
htmlInfoMsg: "Boardsize 19x19 - 20 minutes per side"

# ???
# type: str
# required
sgfDir: "SGF"

# ???
# type: bool
# optional
# default: false
compressSgf: true

# ???
# type: float
# required
provisionalAge: 0.04

# ???
# type: float
# required
establishedAge: 31.0

# ???
# type: str
# required
killFileSrv: "<server-code>/kill_cgos19"

# ???
# type: str
# required
killFileWeb: "<server-code>/kill_webuild19"

# ???
# type: float
# optional
# default: 0.10
anchor_match_rate: 0.10

#!!! this should be made optional !!!
# ???
# type: str
# required
bad_users_file: null

#!!! this should be made optional !!!
# ???
# type: int
# required
moves_per_save: 1

# ???
# type: bool
# optional
# default: false
hashPassword: false

# ???
# type: str
# optional
# default: "AUTO"
# possible values: "AUTO", "ADMIN"
matchMode: "AUTO"
